### ISSUE TITLE
Is LeapMotion needed?

### ISSUE THREAD

**Issue by Eulerianial** [kathawala/hands-on-math#1]
Hello, I tried running it in browser but I think mouse interactivity is not there. Is it only through LeapMotion?

**Comment by aashnashroff** [comment]
Yes, the program does not have any functionality without the Leap Motion.

**Comment by Eulerianial** [comment]
We are building an ed-tech company at Amsterdam. Really interested in hand-on-math and further development. Would it be possible to schedule a quick meeting with your team and discuss few things?

**Comment by kathawala** [comment]
@Eulerianial 

Please be aware that this is a GPL-ed program, meaning that if you use it in your application or modify it for distribution you must also distribute the source code when requested. This ensures that we can benefit from your modifications (e.g. if you were able to add mouse control).

That being said, if you want to discuss things with us, feel free. We are both on tight schedules, but if you email me I'll try to respond quickly.
